### ISSUE TITLE
App doesn't compile with BG5 Plugin installed

### ISSUE THREAD

**Issue by saeho** [iHealthLab/plugin-ihealth-bg#1] opened 2015-07-29 18:34 UTC
Steps to reproduce this issue:

1. Create new app
2. meteor add-platform android
3. meteor add cordova:com.ihealth.plugin.bgmanagercordova@https://github.com/iHealthLab/plugin-ihealth-bg/tarball/485ecc5d5fd9165a93bf1b45ddcee4faa18e48af
4. meteor run android-device

App won't compile because of the plugin.

**Comment by ihealthdavid** [comment] 2015-09-03 18:51
Closing, as this seems to be a duplicate of #6

**Closed by ihealthdavid** 2015-09-03 18:51 UTC
